import { LetterType } from "@/types/model";

export const alphabet: Array<LetterType> = [
  {
    uppercase: 'Ա',
    lowercase: 'ա',
    name: 'Айб',
    transliteration: 'a',
    ipa: 'ɑ',
  },
  {
    uppercase: 'Բ',
    lowercase: 'բ',
    name: 'Бен',
    transliteration: 'b',
    ipa: 'b',
  },
  {
    uppercase: 'Գ',
    lowercase: 'գ',
    name: 'Гим',
    transliteration: 'g',
    ipa: 'g',
  },
  {
    uppercase: 'Դ',
    lowercase: 'դ',
    name: 'Да',
    transliteration: 'd',
    ipa: 'd',
  },
  {
    uppercase: 'Ե',
    lowercase: 'ե',
    name: 'Эдж',
    transliteration: 'e',
    ipa: ['ɛ', 'jɛ'],
  },
  {
    uppercase: 'Զ',
    lowercase: 'զ',
    name: 'За',
    transliteration: 'z',
    ipa: 'z',
  },
  {
    uppercase: 'Է',
    lowercase: 'է',
    name: 'Э',
    transliteration: 'ē',
    ipa: 'e',
  },
  {
    uppercase: 'Ը',
    lowercase: 'ը',
    name: 'Ыт',
    transliteration: 'ə',
    ipa: 'ə',
  },
  {
    uppercase: 'Թ',
    lowercase: 'թ',
    name: 'То',
    transliteration: 'tʻ',
    ipa: 'tʰ',
  },
  {
    uppercase: 'Ժ',
    lowercase: 'ժ',
    name: 'Же',
    transliteration: 'ž',
    ipa: 'ʒ',
  },
  {
    uppercase: 'Ի',
    lowercase: 'ի',
    name: 'Ини',
    transliteration: 'i',
    ipa: 'i',
  },
  {
    uppercase: 'Լ',
    lowercase: 'լ',
    name: 'Льюн',
    transliteration: 'l',
    ipa: 'l',
  },
  {
    uppercase: 'Խ',
    lowercase: 'խ',
    name: 'Хе',
    transliteration: 'x',
    ipa: 'χ',
  },
  {
    uppercase: 'Ծ',
    lowercase: 'ծ',
    name: 'Тьца',
    transliteration: 'c',
    ipa: 't͡s',
  },
  {
    uppercase: 'Կ',
    lowercase: 'կ',
    name: 'Кен',
    transliteration: 'k',
    ipa: 'k',
  },
  {
    uppercase: 'Հ',
    lowercase: 'հ',
    name: 'Хо',
    transliteration: 'h',
    ipa: 'h',
  },
  {
    uppercase: 'Ձ',
    lowercase: 'ձ',
    name: 'Дза',
    transliteration: 'j',
    ipa: 'd͡z',
  },
  {
    uppercase: 'Ղ',
    lowercase: 'ղ',
    name: 'Гхат',
    transliteration: 'ł',
    ipa: ['l', 'ɫ'],
  },
  {
    uppercase: 'Ճ',
    lowercase: 'ճ',
    name: 'Тче',
    transliteration: 'č',
    ipa: 't͡ʃ',
  },
  {
    uppercase: 'Մ',
    lowercase: 'մ',
    name: 'Мен',
    transliteration: 'm',
    ipa: 'm',
  },
  {
    uppercase: 'Յ',
    lowercase: 'յ',
    name: 'Йи',
    transliteration: 'y',
    ipa: 'j',
  },
  {
    uppercase: 'Ն',
    lowercase: 'ն',
    name: 'Ну',
    transliteration: 'n',
    ipa: ['n', 'ŋ'],
  },
  {
    uppercase: 'Շ',
    lowercase: 'շ',
    name: 'Ша',
    transliteration: 'š',
    ipa: 'ʃ',
  },
  {
    uppercase: 'Ո',
    lowercase: 'ո',
    name: 'Во',
    transliteration: 'o',
    ipa: ['o', 'ʋɔ'],
  },
  {
    uppercase: 'Չ',
    lowercase: 'չ',
    name: 'Ча',
    transliteration: 'č̣',
    ipa: 't͡ʃʰ',
  },
  {
    uppercase: 'Պ',
    lowercase: 'պ',
    name: 'Пе',
    transliteration: 'p',
    ipa: 'p',
  },
  {
    uppercase: 'Ջ',
    lowercase: 'ջ',
    name: 'Дже',
    transliteration: 'ǰ',
    ipa: 'd͡ʒ',
  },
  {
    uppercase: 'Ռ',
    lowercase: 'ռ',
    name: 'Ра',
    transliteration: 'ṙ',
    ipa: 'r',
  },
  {
    uppercase: 'Ս',
    lowercase: 'ս',
    name: 'Се',
    transliteration: 's',
    ipa: 's',
  },
  {
    uppercase: 'Վ',
    lowercase: 'վ',
    name: 'Вев',
    transliteration: 'v',
    ipa: ['v', 'ʋ'],
  },
  {
    uppercase: 'Տ',
    lowercase: 'տ',
    name: 'Тюн',
    transliteration: 't',
    ipa: 't',
  },
  {
    uppercase: 'Ր',
    lowercase: 'ր',
    name: 'Ре',
    transliteration: 'r',
    ipa: 'ɹ',
  },
  {
    uppercase: 'Ց',
    lowercase: 'ց',
    name: 'Цо',
    transliteration: 'c̣',
    ipa: 'tsʰ',
  },
  {
    uppercase: 'Ւ',
    lowercase: 'ւ',
    name: 'Йюн',
    transliteration: 'w',
    ipa: 'w',
  },
  {
    uppercase: 'Փ',
    lowercase: 'փ',
    name: 'Пьюр',
    transliteration: 'pʻ',
    ipa: 'pʰ',
  },
  {
    uppercase: 'Ք',
    lowercase: 'ք',
    name: 'Ке',
    transliteration: 'kʻ',
    ipa: 'kʰ',
  },
  {
    uppercase: 'Եվ',
    lowercase: 'և',
    name: 'Ев',
    transliteration: 'ev',
    ipa: ['jɛv', 'ɛv'],
  },
  {
    uppercase: 'Օ',
    lowercase: 'օ',
    name: 'О',
    transliteration: 'o',
    ipa: 'o',
  },
  {
    uppercase: 'Ֆ',
    lowercase: 'ֆ',
    name: 'Фе',
    transliteration: 'f',
    ipa: 'f',
  },
];
