import type { LetterType } from '@/types/model';

export const alphabet: Array<LetterType> = [
  {
    uppercase: 'Ա',
    lowercase: 'ա',
    name: 'Айб',
    transliteration: 'a',
    ipa: 'ɑ',
    audio: 'Hy-ա',
  },
  {
    uppercase: 'Բ',
    lowercase: 'բ',
    name: 'Бен',
    transliteration: 'b',
    ipa: 'b',
    audio: 'Hy-EA-բ',
  },
  {
    uppercase: 'Գ',
    lowercase: 'գ',
    name: 'Гим',
    transliteration: 'g',
    ipa: 'g',
    audio: 'Hy-EA-գ',
  },
  {
    uppercase: 'Դ',
    lowercase: 'դ',
    name: 'Да',
    transliteration: 'd',
    ipa: 'd',
    audio: 'Hy-EA-դ',
  },
  {
    uppercase: 'Ե',
    lowercase: 'ե',
    name: 'Эдж',
    transliteration: ['e', 'ye'],
    ipa: ['ɛ', 'jɛ'],
    audio: 'Hy-ե',
  },
  {
    uppercase: 'Զ',
    lowercase: 'զ',
    name: 'За',
    transliteration: 'z',
    ipa: 'z',
    audio: 'Hy-զ',
  },
  {
    uppercase: 'Է',
    lowercase: 'է',
    name: 'Э',
    transliteration: 'e',
    ipa: 'e',
    audio: 'Hy-է',
  },
  {
    uppercase: 'Ը',
    lowercase: 'ը',
    name: 'Ыт',
    transliteration: 'y',
    ipa: 'ə',
    audio: 'Hy-ը',
  },
  {
    uppercase: 'Թ',
    lowercase: 'թ',
    name: 'То',
    transliteration: 't’',
    ipa: 'tʰ',
    audio: 'Hy-թ',
  },
  {
    uppercase: 'Ժ',
    lowercase: 'ժ',
    name: 'Же',
    transliteration: 'zh',
    ipa: 'ʒ',
    audio: 'Hy-ժ',
  },
  {
    uppercase: 'Ի',
    lowercase: 'ի',
    name: 'Ини',
    transliteration: 'i',
    ipa: 'i',
    audio: 'Hy-ի',
  },
  {
    uppercase: 'Լ',
    lowercase: 'լ',
    name: 'Льюн',
    transliteration: 'l',
    ipa: 'l',
    audio: 'Hy-լ',
  },
  {
    uppercase: 'Խ',
    lowercase: 'խ',
    name: 'Хе',
    transliteration: 'kh',
    ipa: 'χ',
    audio: 'Hy-խ',
  },
  {
    uppercase: 'Ծ',
    lowercase: 'ծ',
    name: 'Тьца',
    transliteration: 'ts',
    ipa: 't͡s',
    audio: 'Hy-EA-ծ',
  },
  {
    uppercase: 'Կ',
    lowercase: 'կ',
    name: 'Кен',
    transliteration: 'k',
    ipa: 'k',
    audio: 'Hy-EA-կ',
  },
  {
    uppercase: 'Հ',
    lowercase: 'հ',
    name: 'Хо',
    transliteration: 'h',
    ipa: 'h',
    audio: 'Hy-հ',
  },
  {
    uppercase: 'Ձ',
    lowercase: 'ձ',
    name: 'Дза',
    transliteration: 'dz',
    ipa: 'd͡z',
    audio: 'Hy-EA-ձ',
  },
  {
    uppercase: 'Ղ',
    lowercase: 'ղ',
    name: 'Гхат',
    transliteration: 'gh',
    ipa: ['ʁ', 'ɫ'],
    audio: 'Hy-ղ',
  },
  {
    uppercase: 'Ճ',
    lowercase: 'ճ',
    name: 'Тче',
    transliteration: 'ch',
    ipa: 't͡ʃ',
    audio: 'Hy-EA-ճ',
  },
  {
    uppercase: 'Մ',
    lowercase: 'մ',
    name: 'Мен',
    transliteration: 'm',
    ipa: 'm',
    audio: 'Hy-մ',
  },
  {
    uppercase: 'Յ',
    lowercase: 'յ',
    name: 'Йи',
    transliteration: 'y',
    ipa: 'j',
    audio: 'Hy-յ',
  },
  {
    uppercase: 'Ն',
    lowercase: 'ն',
    name: 'Ну',
    transliteration: 'n',
    ipa: ['n', 'ŋ'],
    audio: 'Hy-ն',
  },
  {
    uppercase: 'Շ',
    lowercase: 'շ',
    name: 'Ша',
    transliteration: 'sh',
    ipa: 'ʃ',
    audio: 'Hy-շ',
  },
  {
    uppercase: 'Ո',
    lowercase: 'ո',
    name: 'Во',
    transliteration: ['o', 'vo'],
    ipa: ['o', 'ʋɔ'],
    audio: 'Hy-ո',
  },
  {
    uppercase: 'Չ',
    lowercase: 'չ',
    name: 'Ча',
    transliteration: 'ch’',
    ipa: 't͡ʃʰ',
    audio: 'Hy-չ',
  },
  {
    uppercase: 'Պ',
    lowercase: 'պ',
    name: 'Пе',
    transliteration: 'p',
    ipa: 'p',
    audio: 'Hy-EA-պ',
  },
  {
    uppercase: 'Ջ',
    lowercase: 'ջ',
    name: 'Дже',
    transliteration: 'j',
    ipa: 'd͡ʒ',
    audio: 'Hy-EA-ջ',
  },
  {
    uppercase: 'Ռ',
    lowercase: 'ռ',
    name: 'Ра',
    transliteration: 'rr',
    ipa: 'r',
    audio: 'Hy-ռ',
  },
  {
    uppercase: 'Ս',
    lowercase: 'ս',
    name: 'Се',
    transliteration: 's',
    ipa: 's',
    audio: 'Hy-ս',
  },
  {
    uppercase: 'Վ',
    lowercase: 'վ',
    name: 'Вев',
    transliteration: 'v',
    ipa: ['v', 'ʋ'],
    audio: 'Hy-վ',
  },
  {
    uppercase: 'Տ',
    lowercase: 'տ',
    name: 'Тюн',
    transliteration: 't',
    ipa: 't',
    audio: 'Hy-EA-տ',
  },
  {
    uppercase: 'Ր',
    lowercase: 'ր',
    name: 'Ре',
    transliteration: 'r',
    ipa: 'ɹ',
    audio: 'Hy-ր',
  },
  {
    uppercase: 'Ց',
    lowercase: 'ց',
    name: 'Цо',
    transliteration: 'ts’',
    ipa: 'tsʰ',
    audio: 'Hy-ց',
  },
  {
    uppercase: 'Ւ',
    lowercase: 'ւ',
    name: 'Йюн',
    transliteration: 'w',
    ipa: 'w',
    audio: 'Hy-ւ',
  },
  {
    uppercase: 'Փ',
    lowercase: 'փ',
    name: 'Пьюр',
    transliteration: 'p’',
    ipa: 'pʰ',
    audio: 'Hy-փ',
  },
  {
    uppercase: 'Ք',
    lowercase: 'ք',
    name: 'Ке',
    transliteration: 'k’',
    ipa: 'kʰ',
    audio: 'Hy-ք',
  },
  {
    uppercase: 'Եվ',
    lowercase: 'և',
    name: 'Ев',
    transliteration: ['ev', 'yev'],
    ipa: ['ɛv', 'jɛv'],
    audio: 'Hy-եւ',
  },
  {
    uppercase: 'Օ',
    lowercase: 'օ',
    name: 'О',
    transliteration: 'o',
    ipa: 'o',
    audio: 'Hy-օ',
  },
  {
    uppercase: 'Ֆ',
    lowercase: 'ֆ',
    name: 'Фе',
    transliteration: 'f',
    ipa: 'f',
    audio: 'Hy-ֆ',
  },
  {
    uppercase: ['Ու', 'ՈՒ'],
    lowercase: 'ու',
    name: 'У',
    transliteration: 'u',
    ipa: 'u',
    audio: 'Hy-ու',
  },
].map((letter) => ({
  ...letter,
  id: `${letter.transliteration}_${letter.ipa}`,
}));
