import type { WordData } from '@/types/model';

export const wordExamples: Record<string, WordData> = {
  ա: ['առյուծ', 'arryuts', 'лев', 'lion'],
  բ: ['բադիկ', 'badik', 'утёнок', 'duckling'],
  գ: ['գորգ', 'gorg', 'ковёр', 'carpet'],
  դ: ['դելֆին', 'delfin', 'дельфин', 'dolphin'],
  ե: ['եղնիկ', 'yeghnik', 'олень', 'deer'],
  զ: ['զեբրա', 'zebra', 'зебра', 'zebra'],
  է: ['էքսկավատոր', 'ek’skavator', 'экскаватор', 'excavator'],
  ը: ['ընձուղտ', 'yndzught', 'жираф', 'giraffe'],
  թ: ['թութակ', 't’ut’ak', 'попугай', 'parrot'],
  ժ: ['ժամացույց', 'zhamats’uyts', 'часы', 'clock'],
  ի: ['ինքնաթիռ', 'ink’nat’irr', 'самолёт', 'airplane'],
  լ: ['լուսին', 'lusin', 'луна', 'moon'],
  խ: ['խնձոր', 'khndzor', 'яблоко', 'apple'],
  ծ: ['ծաղիկ', 'tsaghik', 'цветок', 'flower'],
  կ: ['կապիկ', 'kapik', 'обезьяна', 'monkey'],
  հ: ['հեծանիվ', 'hetsaniv', 'велосипед', 'bike'],
  ձ: ['ձւկ', 'dzuk', 'рыба', 'fish'],
  ղ: ['ղեկ', 'ghek', 'руль', 'wheel'],
  ճ: ['ճուտիկ', 'chutik', 'птенец', 'chick'],
  մ: ['մեղու', 'meghu', 'пчела', 'bee'],
  յ: ['յասաման', 'yasaman', 'сирень', 'lilac'],
  ն: ['նապաստակ', 'napastak', 'заяц', 'hare'],
  շ: ['շուն', 'shun', 'собака', 'dog'],
  ո: ['ոզնի', 'vozni', 'ёж', 'hedgehog'],
  չ: ['չղջիկ', 'ch’ghjik', 'летучая мышь', 'bat'],
  պ: ['պինգվին', 'pingvin', 'пингвин', 'penguin'],
  ջ: ['ջութակ', 'jut’ak', 'скрипка', 'violin'],
  ռ: ['ռադիո', 'rradio', 'радио', 'radio'],
  ս: ['սկյուռիկ', 'skyurrik', 'белка', 'squirrel'],
  վ: ['վագր', 'vagr', 'тигр', 'tiger'],
  տ: ['տերև', 'terev', 'лист', 'leaf'],
  ր: ['մեղր', 'meghr', 'мёд', 'honey'],
  ց: ['ցուլ', 'ts’ul', 'бык', 'bull'],
  ու: ['ուղտ', 'ught', 'верблюд', 'camel'],
  փ: ['փիղ', 'p’igh', 'слон', 'elephant'],
  ք: ['քար', 'k’ar', 'камень', 'stone'],
  և: ['արև', 'arev', 'солнце', 'sun'],
  օ: ['օձ', 'odz', 'змея', 'snake'],
  ֆ: ['ֆլամինգո', 'flamingo', 'фламинго', 'flamingos'],
};
