import { LetterType } from "./model";

export const alphabet: Array<LetterType> = [
  {
    uppercase: 'Ա',
    lowercase: 'ա',
    name: 'ayb',
    transliteration: 'a',
  },
  {
    uppercase: 'Բ',
    lowercase: 'բ',
    name: 'ben',
    transliteration: 'b',
  },
  {
    uppercase: 'Գ',
    lowercase: 'գ',
    name: 'gim',
    transliteration: 'g',
  },
  {
    uppercase: 'Դ',
    lowercase: 'դ',
    name: 'da',
    transliteration: 'd',
  },
  {
    uppercase: 'Ե',
    lowercase: 'ե',
    name: 'eč̣',
    transliteration: 'e',
  },
  {
    uppercase: 'Զ',
    lowercase: 'զ',
    name: 'za',
    transliteration: 'z',
  },
  {
    uppercase: 'Է',
    lowercase: 'է',
    name: 'ē',
    transliteration: 'ē',
  },
  {
    uppercase: 'Ը',
    lowercase: 'ը',
    name: 'ətʻ',
    transliteration: 'ə',
  },
  {
    uppercase: 'Թ',
    lowercase: 'թ',
    name: 'tʻo',
    transliteration: 'tʻ',
  },
  {
    uppercase: 'Ժ',
    lowercase: 'ժ',
    name: 'žē',
    transliteration: 'ž',
  },
  {
    uppercase: 'Ի',
    lowercase: 'ի',
    name: 'ini',
    transliteration: 'i',
  },
  {
    uppercase: 'Լ',
    lowercase: 'լ',
    name: 'liwn',
    transliteration: 'l',
  },
  {
    uppercase: 'Խ',
    lowercase: 'խ',
    name: 'xē',
    transliteration: 'x',
  },
  {
    uppercase: 'Ծ',
    lowercase: 'ծ',
    name: 'ca',
    transliteration: 'c',
  },
  {
    uppercase: 'Կ',
    lowercase: 'կ',
    name: 'ken',
    transliteration: 'k',
  },
  {
    uppercase: 'Հ',
    lowercase: 'հ',
    name: 'ho',
    transliteration: 'h',
  },
  {
    uppercase: 'Ձ',
    lowercase: 'ձ',
    name: 'ja',
    transliteration: 'j',
  },
  {
    uppercase: 'Ղ',
    lowercase: 'ղ',
    name: 'łat',
    transliteration: 'ł',
  },
  {
    uppercase: 'Ճ',
    lowercase: 'ճ',
    name: 'čē',
    transliteration: 'č',
  },
  {
    uppercase: 'Մ',
    lowercase: 'մ',
    name: 'men',
    transliteration: 'm',
  },
  {
    uppercase: 'Յ',
    lowercase: 'յ',
    name: 'yi',
    transliteration: 'y',
  },
  {
    uppercase: 'Ն',
    lowercase: 'ն',
    name: 'nu',
    transliteration: 'n',
  },
  {
    uppercase: 'Շ',
    lowercase: 'շ',
    name: 'ša',
    transliteration: 'š',
  },
  {
    uppercase: 'Ո',
    lowercase: 'ո',
    name: 'o',
    transliteration: 'o',
  },
  {
    uppercase: 'Չ',
    lowercase: 'չ',
    name: 'č̣a',
    transliteration: 'č̣',
  },
  {
    uppercase: 'Պ',
    lowercase: 'պ',
    name: 'pē',
    transliteration: 'p',
  },
  {
    uppercase: 'Ջ',
    lowercase: 'ջ',
    name: 'ǰē',
    transliteration: 'ǰ',
  },
  {
    uppercase: 'Ռ',
    lowercase: 'ռ',
    name: 'ṙa',
    transliteration: 'ṙ',
  },
  {
    uppercase: 'Ս',
    lowercase: 'ս',
    name: 'sē',
    transliteration: 's',
  },
  {
    uppercase: 'Վ',
    lowercase: 'վ',
    name: 'vew',
    transliteration: 'v',
  },
  {
    uppercase: 'Տ',
    lowercase: 'տ',
    name: 'tiwn',
    transliteration: 't',
  },
  {
    uppercase: 'Ր',
    lowercase: 'ր',
    name: 'rē',
    transliteration: 'r',
  },
  {
    uppercase: 'Ց',
    lowercase: 'ց',
    name: 'c̣o',
    transliteration: 'c̣',
  },
  {
    uppercase: 'Ւ',
    lowercase: 'ւ',
    name: 'hiwn',
    transliteration: 'w',
  },
  {
    uppercase: 'Փ',
    lowercase: 'փ',
    name: 'pʻiwr',
    transliteration: 'pʻ',
  },
  {
    uppercase: 'Ք',
    lowercase: 'ք',
    name: 'kʻē',
    transliteration: 'kʻ',
  },
  {
    uppercase: 'Օ',
    lowercase: 'օ',
    name: 'o',
    transliteration: 'o',
  },
  {
    uppercase: 'Ֆ',
    lowercase: 'ֆ',
    name: 'fē',
    transliteration: 'f',
  },
];
